project:
  type: website
  output-dir: docs
execute:
  freeze: auto
knitr:
  opts_knit:
    verbose: false
website:
  #title: "Intro to Bayes"
  navbar:
    #logo: /misc/Thomas_Bayes.gif
    background: primary
    left:
      - href: index.qmd
        text: Home
        
  page-footer:
    center:
      - text: "Intro to Bayes"       
      #href: stealourcourse.qmd
    right:
      - icon: github
        href: https://github.com/mattiasvillani/interactive_intro
        aria-label: Quarto GitHub
format:
  html:
    theme:
      dark: superhero # litera, lumen, superhero, united
      light: lumen
    css: styles.css
    toc: true
    toc-title: Sections
    #monobackgroundcolor: #c3d0e6
callout-appearance: default




